# Generated by Django 4.2.16 on 2024-11-21 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviearticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ending',
            name='like_users',
            field=models.ManyToManyField(default=None, related_name='like_endings', to=settings.AUTH_USER_MODEL),
        ),
    ]
