# Generated by Django 4.2.16 on 2024-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviearticles', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
