# Generated by Django 4.2.16 on 2024-11-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviearticles', '0004_rename_title_ending_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ending',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
